source "https://rubygems.org"

gem "rails", "4.2.0"
gem "dotenv-rails"
gem "sqlite3"
gem "unicorn"

# Frontend
gem "bourbon"
gem "bitters"
gem "coffee-rails", "~> 4.1.0"
gem "flutie"
gem "font-awesome-rails"
gem "haml-rails"
gem "handlebars_assets"
gem "jquery-rails"
gem "lodash-rails"
gem "modulejs-rails"
gem "neat"
gem "refills"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
